function __cuvis_help -d "Show help"
    echo "cuvis - Manage CUDA device visibility"
    echo ""
    echo "USAGE:"
    echo "    cuvis set <devices>    Set visible CUDA devices"
    echo "    cuvis info             Show current device visibility"
    echo "    cuvis unset            Unset device visibility (show all)"
    echo "    cuvis --help           Show this help"
    echo ""
    echo "DEVICE FORMATS:"
    echo "    1,2,3        Use devices 1, 2, and 3"
    echo "    2-5          Use devices 2 through 5"
    echo "    1,3-5        Use device 1 and devices 3 through 5"
    echo "    0            Use only device 0"
end
